#undef TAPPING_TERM
#define TAPPING_TERM 175

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 7

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 8

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 6

#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "DRZzE/VqaNqd"
#define LAYER_STATE_16BIT

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

